### ISSUE TITLE
Where can we download the scanned images?

### ISSUE THREAD

**Issue by leitro** [DataScienceUIBK/ChroniclingAmericaQA#1]
Hi! Thank you for the excellent contribution in proposing the new QA dataset. The JSON files contain only text data, could you please let us know where we can download the scanned images?

**Comment by bhawnapiryani** [comment]
Hi, Thank you for your interest in our QA dataset!

We have updated the dataset, and it now includes the corrected OCR text as context, the raw OCR text, and a URL for each entry that you can use to download the corresponding scanned newspaper page. Since the dataset was created using resources from Chronicling America, the original scanned images are accessible via the URLs provided in the dataset, which link directly to the Chronicling America website.

For example, a typical URL in the dataset might look like this:
https://chroniclingamerica.loc.gov/lccn/sn83025588/1803-01-25/ed-1/seq-4.json

This JSON contains links to various formats, such as:

**JP2 Image:** https://chroniclingamerica.loc.gov/lccn/sn83025588/1803-01-25/ed-1/seq-4.jp2
**PDF:** https://chroniclingamerica.loc.gov/lccn/sn83025588/1803-01-25/ed-1/seq-4.pdf
**OCR Text:** https://chroniclingamerica.loc.gov/lccn/sn83025588/1803-01-25/ed-1/seq-4/ocr.txt

You can extract and download the format you require directly from these links.

**Comment by leitro** [comment]
Amazing! Thank you!
